# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-08 01:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='gamename',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='owner',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
