# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-09 03:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20160808_0212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='begindate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='enddate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
