# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-15 08:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_matchlist_team_b_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='teamcount',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
