# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-16 05:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_tournament_teamcount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teamid', models.CharField(max_length=30)),
                ('teamname', models.CharField(blank=True, max_length=100, null=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Game')),
            ],
        ),
        migrations.AlterField(
            model_name='matchlist',
            name='team_a',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='matchlist',
            name='team_b',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
