# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-20 02:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_tournamentteam'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentteam',
            name='matchid',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='tournamentteam',
            name='teamside',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
