# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-24 01:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20160820_0251'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentteam',
            name='matchseq',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
