# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-27 10:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_tournamentteam_matchseq'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='mastername',
            field=models.CharField(default='', max_length=30),
        ),
    ]
