# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-15 07:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0016_auto_20161028_0523'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoardCont',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boardtype', models.CharField(blank=True, max_length=30, null=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('cont', models.TextField(blank=True, null=True)),
                ('hits', models.IntegerField()),
                ('insertdate', models.DateField(blank=True, null=True)),
                ('updatedate', models.DateField(blank=True, null=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Game')),
                ('insertuser', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
