# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-15 07:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_boardcont'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardcont',
            name='game',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Game'),
        ),
    ]
