# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-20 16:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_auto_20161115_0739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardcont',
            name='insertdate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='boardcont',
            name='updatedate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
