# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-28 03:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_auto_20161128_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='poster',
            field=models.ImageField(upload_to='static/img/poster/'),
        ),
    ]
