# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-28 06:25
from __future__ import unicode_literals

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_auto_20161128_1250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='poster',
            field=models.ImageField(upload_to=main.models.get_image_path),
        ),
    ]
